version: "3"
services:

  model_nasa_rwanda_field_boundary_competition_gold_v1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nasa-rwanda
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]